version: 2.1

workflows:
  version: 2
  all-checks:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:16.17.1
    steps:
      - run:
          name: Install Git Large File Storage (LFS)
          command: sudo apt-get install git-lfs
      - run:
          name: Install protoc
          # protobuf-compiler from package management too old
          # https://packages.debian.org/buster/protobuf-compiler
          working_directory: /tmp
          command: |
            wget -O protoc-linux-x86_64.zip "https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-x86_64.zip"
            unzip protoc-linux-x86_64.zip -d ./protoc-linux-x86_64
            sudo ln -s $(realpath ./protoc-linux-x86_64/bin/protoc) /usr/local/bin/protoc
            echo "protoc version:" && protoc --version
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule init && git submodule update
      - run:
          name: Version information
          command: echo "node $(node --version)"; echo "npm $(npm --version)"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Generate code (.proto -> .ts)
          command: npm run codegen
      - run:
          name: Ensure schemas are up-to-date
          command: |
            CHANGES_IN_REPO=$(git status --porcelain)
            if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
              git status && git --no-pager diff
              exit 1
            fi
      - run:
          name: Build (.ts -> .js/.d.ts)
          command: npm run build
