# See https://doc.mergify.io/configuration.html

pull_request_rules:
  - name: automerge to main with label automerge
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge
      - label!=WIP
      # We need to list them all individually. Here is why: https://doc.mergify.io/conditions.html#validating-all-status-check
      - "status-success=ci/circleci: build"
      - "status-success=ci/circleci: coverage"
      - "status-success=ci/circleci: docs-build"
      - "status-success=ci/circleci: lint"
      - "status-success=ci/circleci: test"
      - "status-success=ci/circleci: test-chrome"
    actions:
      merge:
        method: merge
        strict: false
