#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail
command -v shellcheck >/dev/null && shellcheck "$0"

rm -rf "proto"
mkdir -p "proto"
echo "Autogenerated folder, see export_protos.sh" > "proto/README.md"

buf export "/aioz/src/go-aioz/proto" --output "proto"